### ISSUE TITLE
piePlot 

### ISSUE THREAD

**Issue by NicoleSchr** [umahajanatlmu/metapacR#10]
Error in grDevices::pdf(file = filename, ....m version = version) : 
cannot open file in "~blabla/resultsi/piePlots_icontrol -ko.pdf"

I think there is a mistake with the sep ="i" here:

else if (save != "none") {
      ggsave(
        filename = paste(path, "/piePlots_", paste0(i, ".", save), sep = "i"),
        plot = p,
        width = fig.width,
        height = fig.height,
        dpi = dpi

i think it should be sep = "" ?

**Comment by umahajanatlmu** [comment]
corrected
