### ISSUE TITLE
plotDiamReduction.R

### ISSUE THREAD

**Issue by NicoleSchr** [umahajanatlmu/metapacR#8]
Plotting was not possible, I think the error is here:

## ----------------------------------------------------------------
  select.markers <- dist.variables
  imputed.data <- imputed.data[, colnames(imputed.data) %in% select.markers, drop = FALSE]

dist.variable will give an error:
ERROR: [1] "no distribution variable listed"

possible solution ?:
select.markers <- colnames(expData$imputed.data)

p <- metapacR::plotDiamReduction(dataList = expData,
                            results = diam_reduction,
                            diam.method = "opls",
                            grouping.variables = "GROUP",
                            dist.variables = select.markers)

**Comment by umahajanatlmu** [comment]
resolved
